name: Publish to Maven Central

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Import GPG key and upload to keyserver
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          echo "$SIGNING_KEY" | gpg --batch --import
          KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2)
          echo "Uploading key $KEY_ID to keyservers..."
          gpg --keyserver keyserver.ubuntu.com --send-keys $KEY_ID || true
          gpg --keyserver keys.openpgp.org --send-keys $KEY_ID || true
          gpg --keyserver pgp.mit.edu --send-keys $KEY_ID || true

      - name: Publish to Central Portal
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}           # ASCII-armored private key
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }} # passphrase
        run: |
          ./gradlew \
            publishToCentralPortal \
            --no-daemon
